"""empty message

Revision ID: 22dbcbdd5f89
Revises: None
Create Date: 2016-01-15 01:23:12.857725

"""

# revision identifiers, used by Alembic.
revision = '22dbcbdd5f89'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    op.add_column('games', sa.Column('player1', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('player2', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'users', ['player1'], ['id'])
    op.create_foreign_key(None, 'games', 'users', ['player2'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'player2')
    op.drop_column('games', 'player1')
    op.create_table('entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='entries_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='entries_pkey')
    )
    ### end Alembic commands ###
